prefix: /hlilab/21data/collections/cancer-pair/
pwd: /hlilab/alvin/pangenome_sv_benchmarking/canres_comm_analysis/phaseA_subsampled_som
minimap2: /hlilab/alvin/pangenome_sv_benchmarking/1a.alignment_sv_tools/minimap2/minimap2
samtools: /hlilab/alvin/pangenome_sv_benchmarking/1a.alignment_sv_tools/samtools/samtools

samples:
  tumor:
      - HCC1395
      - COLO829
      - COLO829
      - HCC1937
      - HCC1954
      - NCI1437
      - NCI2009
  platform:
      - hifi1
      - hifi1
      - ont1
      - hifi1
      - hifi1
      - hifi1
      - hifi1

assembly:
  - grch38
