prefix: /cluster/hlilab/alvin/severus_data
pwd: /cluster/hlilab/alvin/severus_data

samples:
  tumor:
      - H1437
      - HCC1395
      - H2009
      - HCC1954
  platform:
      - ont1
      - ont1
      - ont1
      - ont1

assembly:
  - chm13
  - grch38

mosaic: False
