pwd: /hlilab/alvin/pangenome_sv_benchmarking/7.nanopore_evaluation

samples:
  normal:
      batch1:
          dir: ../1c.additional_ont/
          cell_line:
              - HG002rep1
              - HG002rep2
      batch2:
          dir: ../1c.additional_ont/
          cell_line:
              - COLO829BL
      batch3:
          dir: /cluster/hlilab/alvin/severus_data/
          cell_line:
              - H1437
              - HCC1395
              - H2009
              - HCC1954
  #tumor_only:
  #    tumor:
  #        - HCC1395
  #        - HCC1937
  #        - HCC1954
  #    platform:
  #        - ont1
  #        - ont1
  #        - ont1

  #tumor_normal_pair:
  #    batch1:
  #        dir: ../1c.additional_ont/
  #        tumor:
  #            - COLO829
  #        platform:
  #            - ont1
  #    batch2:
  #        dir: /cluster/hlilab/alvin/severus_data/
  #        tumor:
  #            - COLO829
  #        platform:
  #            - ont1
  #    batch3:
  #        dir: /cluster/hlilab/alvin/severus_data2
  #        tumor:
  #            - COLO829
  #        platform:
  #            - ont1

reg:
  chm13: ../4.gafcall_evaluation/chm13.reg.bed
  grch38: ../4.gafcall_evaluation/grch38.reg.bed
