prefix: /hlilab/21data/collections/cancer-pair/
pwd: /hlilab/alvin/pangenome_sv_benchmarking/1a.alignment_sv_tools

samples:
  tumor:
      - HCC1395
      - COLO829
      - COLO829
      - COLO829
      - HCC1937
      - HCC1954
      - NCI1437
      - NCI2009
  platform:
      - hifi1
      - hifi1
      - ont1
      - ont2
      - hifi1
      - hifi1
      - hifi1
      - hifi1

assembly:
  - chm13
  - grch38

mosaic: False
